USE ARTICULOABM
GO
INSERT INTO MARCAS VALUES ('MO', 'MOTOROLA');
INSERT INTO MARCAS VALUES ('SA', 'SAMSUNG');
INSERT INTO MARCAS VALUES ('LG', 'LG');
INSERT INTO MARCAS VALUES ('PH', 'PHILIPS');
INSERT INTO MARCAS VALUES ('GE', 'GENERICO');
GO
INSERT INTO LINEAS VALUES ('CE','CELULAR');
INSERT INTO LINEAS VALUES ('TV','TELEVISOR');
INSERT INTO LINEAS VALUES ('PA','PARLANTES');
INSERT INTO LINEAS VALUES ('RF','HELADERAS');
INSERT INTO LINEAS VALUES ('AC','AIRE ACONDICIONADO');
GO
INSERT INTO ARTICULOS VALUES ('MOE5','1','1','MOTOROLA E5',50000,'https://1drv.ms/u/s!Asy75iVQgmj1hEkj28b1BgrRT2l2?e=fQ7hFI');
INSERT INTO ARTICULOS VALUES ('SAA22','2','1','SAMSUNG A22',100000,'https://1drv.ms/u/s!Asy75iVQgmj1hErHTjpUMMVk8T1y?e=1TCuac');
INSERT INTO ARTICULOS VALUES ('MOG32','1','1','MOTOROLA G32',120000,'https://1drv.ms/u/s!Asy75iVQgmj1hEtypcSAq572uEGu?e=1NID4v');
INSERT INTO ARTICULOS VALUES ('LGX86PG','3','2','LG SMART TV 86 PULGADAS',146666,'https://1drv.ms/u/s!Asy75iVQgmj1hExmci2UIOb0uKPa?e=C2hUfw');
INSERT INTO ARTICULOS VALUES ('LGRFLS66','3','4','HELADERA SIDE BY SIDE LG LS66SXSC BRUSHED STEEL',150000,'https://1drv.ms/u/s!Asy75iVQgmj1hE39J3FxsAHE_eMg?e=TmviNa');
